### ISSUE TITLE
UX Review Changes

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#204]
A few changes that came out of the UX review are listed below. Let me know if there are questions or concerns. I will update the Client spec document as well.

In UA Status output:
- Change "inapplicable" to "n/a"
- Change "Technical Support" to "Technical support level"
- Change the support level of "community" to "not included"

In the cloud-init cloud config:
- Change services to "enable" 

```
#cloud-config
ua:
    token: <token-id>
    enable:
        - cis-audit
        - cc
```
