### ISSUE TITLE
Refresh keyrings to correct keys

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#576]
These are the keys that we should be using:

```
esm-new:
  precise: 67C7A026
  trusty-security: 13CB4B13
  trusty-updates: 13CB4B13
fips:
  xenial: EDE22758
fips-updates:
  xenial-updates: EDE22758
cc:
  xenial: 3F491C46
```

I've checked and we have the right key for ESM (as we don't need the precise key), but the others are all currently incorrect.
